language: common-lisp

env:
  matrix:
    - LISP=sbcl COVERALLS=true
    - LISP=ccl

before_install:
  # libuv for Wookie
  - curl -L https://github.com/libuv/libuv/archive/v1.2.0.tar.gz | tar xzf -
  - (cd libuv-1.2.0 && ./autogen.sh && ./configure --prefix=/usr && make && sudo make install)
  # nginx for FastCGI handler
  - sudo add-apt-repository -y ppa:nginx/stable
  - sudo apt-get update -qq
  - sudo apt-get install -qq nginx libfcgi-dev

install:
  # Install cl-travis
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash

before_script:
  - sudo nginx -c t/nginx.conf -p "$PWD/"
  - git clone https://github.com/fukamachi/fast-http ~/lisp/fast-http
  - git clone https://github.com/fukamachi/http-body ~/lisp/http-body
  - git clone https://github.com/fukamachi/lack ~/lisp/lack
  - git clone https://github.com/fukamachi/cl-coveralls ~/lisp/cl-coveralls

script:
  - "cl -l prove -l cl-coveralls
        -e '(or (coveralls:with-coveralls (:exclude (list \"t\" \"v1-compat\"))
                  (every (function identity)
                         (list (prove:run :t-clack-handler-hunchentoot)
                               #-ccl (prove:run :t-clack-handler-wookie)
                               #+sbcl (prove:run :t-clack-handler-fcgi)
                               (prove:run :t-clack-handler-toot)
                               (prove:run :t-clack-v1-compat))))
                (uiop:quit -1))'"
